version: '3'

services:

    myredis:
        image: 'redis:alpine'

    mypostgres:
        image: 'postgres:alpine'
        environment:
            POSTGRES_PASSWORD: '1qaz2wsx'
            POSTGRES_DB: 'myappdb'
            POSTGRES_USER: 'myappuser'
            POSTGRES_HOST: 'mypostgres'
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    mybackend:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./mybackend
        volumes:
            - ./mybackend:/opt/myapp
        environment:
            POSTGRES_PASSWORD: '1qaz2wsx'
            POSTGRES_DB: 'myappdb'
            POSTGRES_USER: 'myappuser'
            POSTGRES_HOST: 'mypostgres'
            REDIS_HOST: 'myredis'
        ports:
            - 127.0.0.1:4000:5000
        depends_on:
            - mypostgres
            - myredis

