    apiVersion: v1
    kind: Service
    metadata:
        name: myfrontend-nodeport
    spec:
        type: NodePort
        ports:
            - targetPort: 3000
              port: 3000
              nodePort: 31200
        selector:
            component: frontend
            app: my-app
