    apiVersion: v1
    kind: Service
    metadata:
        name: myfrontend-clusterip
    spec:
        type: ClusterIP
        ports:
            - targetPort: 3000
              port: 3000
        selector:
            component: frontend
            app: my-app

